"""Recreating all tables correctly

Revision ID: 29ca4a420cc4
Revises: 
Create Date: 2025-03-06 19:08:52.081459

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "29ca4a420cc4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "states_provinces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "country_id", name="uq_state_province"),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("state_province_id", sa.Integer(), nullable=False),
        sa.Column("housing", sa.Float(), nullable=False),
        sa.Column("groceries", sa.Float(), nullable=False),
        sa.Column("transport", sa.Float(), nullable=False),
        sa.Column("healthcare", sa.Float(), nullable=False),
        sa.Column("utilities", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["state_province_id"],
            ["states_provinces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "state_province_id", name="uq_city"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cities")
    op.drop_table("states_provinces")
    op.drop_table("countries")
    # ### end Alembic commands ###
